/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;
import database.IRepositorio;
import database.RepositorioTareas;
import modelo.Tarea;
import modelo.Usuario;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;


public class FormularioTareaFrame extends javax.swing.JFrame {

    private PrincipalFrame ventanaPrincipal;
    private Usuario usuarioActual;
    private Tarea tareaEditar;
    private IRepositorio repositorio; //Uso de interfaz IRepositorio

    private com.toedter.calendar.JDateChooser dateChooser;
    
    public FormularioTareaFrame(PrincipalFrame principal, Usuario usuario, Tarea tarea) {
        this.ventanaPrincipal = principal;
        this.usuarioActual = usuario;
        this.tareaEditar = tarea;
        this.repositorio = new RepositorioTareas();
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        configurarDateChooser();
        aplicarEstilosPersonalizados();
        
        if (tareaEditar != null) {
            cargarDatosTarea();
            this.setTitle("Editar Tarea");
        } else {
            this.setTitle("Nueva Tarea");
        }
        
    }
    
    private void configurarDateChooser() {
        dateChooser = new com.toedter.calendar.JDateChooser();
        dateChooser.setDateFormatString("dd/MM/yyyy");
        dateChooser.setFont(new java.awt.Font("Segoe UI Variable", 0, 12));
        dateChooser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));

        //Reemplazar el txtFechaLimite visualmente
        //Obtener el contenedor padre de txtFechaLimite
        java.awt.Container parent = txtFechaLimite.getParent();

        //Guardar las restricciones de layout
        java.awt.LayoutManager layout = parent.getLayout();
        Object constraints = null;

        if (layout instanceof javax.swing.GroupLayout) {
            // Para GroupLayout, copiar las dimensiones
            dateChooser.setPreferredSize(txtFechaLimite.getPreferredSize());
            dateChooser.setBounds(txtFechaLimite.getBounds());
        }

        //Remover el campo de texto original
        parent.remove(txtFechaLimite);

        // Agregar el date chooser en la misma posición
        parent.add(dateChooser);

        // Actualizar el layout
        parent.revalidate();
        parent.repaint();
    }
    
    private void aplicarEstilosPersonalizados() {
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));

        txtTitulo.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220), 1),
            javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)
        ));

        txtDescripcion.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220), 1),
            javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)
        ));
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setWrapStyleWord(true);

        if (dateChooser != null) {
            dateChooser.setFont(new java.awt.Font("Segoe UI", 0, 13));
        }

        btnGuardar.setFocusPainted(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnCancelar.setFocusPainted(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }
    
    private void cargarDatosTarea() {
        txtTitulo.setText(tareaEditar.getTitulo());
        txtDescripcion.setText(tareaEditar.getDescripcion());
        LocalDate fecha = tareaEditar.getFechaLimite();
        java.util.Date date = java.sql.Date.valueOf(fecha);
        dateChooser.setDate(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtFechaLimite = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabel1.setText("Crear Nueva Tarea");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Titulo:");

        txtTitulo.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        txtTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Descripción:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));
        jScrollPane1.setViewportView(txtDescripcion);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Fecha Limite:");

        txtFechaLimite.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        txtFechaLimite.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));
        txtFechaLimite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaLimiteActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(124, 128, 237));
        btnGuardar.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtFechaLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addComponent(jSeparator2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String titulo = txtTitulo.getText().trim();
        String descripcion = txtDescripcion.getText().trim();

        // Validaciones
        if (titulo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El título es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (dateChooser.getDate() == null) {  // Usar dateChooser
            JOptionPane.showMessageDialog(this, "La fecha límite es obligatoria", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Convertir Date a LocalDate
        java.util.Date fechaSeleccionada = dateChooser.getDate();
        LocalDate fechaLimite = new java.sql.Date(fechaSeleccionada.getTime()).toLocalDate();

        // Guardar o actualizar
        if (tareaEditar == null) {
            // Nueva tarea
            Tarea nuevaTarea = new Tarea(titulo, descripcion, fechaLimite, usuarioActual.getId());
            if (repositorio.crearTarea(nuevaTarea)) {
                JOptionPane.showMessageDialog(this, "Tarea creada correctamente");
                ventanaPrincipal.actualizarTabla();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error al crear tarea", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Editar tarea existente
            tareaEditar.setTitulo(titulo);
            tareaEditar.setDescripcion(descripcion);
            tareaEditar.setFechaLimite(fechaLimite);

            if (repositorio.actualizarTarea(tareaEditar)) {
                JOptionPane.showMessageDialog(this, "Tarea actualizada correctamente");
                ventanaPrincipal.actualizarTabla();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar tarea", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtFechaLimiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaLimiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaLimiteActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtFechaLimite;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

}
